apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: selinuxpolicies.selinux.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.usage
    name: Usage
    type: string
  - JSONPath: .spec.apply
    name: Apply
    type: boolean
  - JSONPath: .status.state
    name: State
    type: string
  group: selinux.openshift.io
  names:
    kind: SelinuxPolicy
    listKind: SelinuxPolicyList
    plural: selinuxpolicies
    singular: selinuxpolicy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SelinuxPolicy is the Schema for the selinuxpolicies API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SelinuxPolicySpec defines the desired state of SelinuxPolicy
          properties:
            apply:
              type: boolean
            policy:
              type: string
          type: object
        status:
          description: SelinuxPolicyStatus defines the observed state of SelinuxPolicy
          properties:
            state:
              description: 'Represents the state that the policy is in. Can be: PENDING,
                IN-PROGRESS, INSTALLED or ERROR'
              type: string
            usage:
              description: Represents the string that the SelinuxPolicy object can
                be referenced as in a pod seLinuxOptions section.
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
