apiVersion: v1
kind: Service
metadata:
  name: selinux-namespace-webhook
  namespace: openshift-selinux-operator
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: selinux-operator-webhook-tls
spec:
  selector:
    app: selinux-operator
  ports:
    - protocol: TCP
      port: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selinux-operator
  namespace: openshift-selinux-operator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selinux-operator
  template:
    metadata:
      labels:
        app: selinux-operator
    spec:
      serviceAccountName: selinux-operator
      containers:
        - name: selinux-operator
          image: "quay.io/jaosorior/selinux-operator:latest"
          command:
          - selinux-operator
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "selinux-operator"
          volumeMounts:
            - name: webhook-tls
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
            
      volumes:
        - name: webhook-tls
          secret:
            secretName: selinux-operator-webhook-tls
