kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: selinux-operator
  namespace: openshift-selinux-operator
subjects:
- kind: ServiceAccount
  name: selinux-operator
roleRef:
  kind: Role
  name: selinux-operator
  apiGroup: rbac.authorization.k8s.io
